### ISSUE TITLE
 java.net.Inet6Address cannot be cast to java.net.Inet4Address

### ISSUE THREAD

**Issue by juforg** [tanhaichao/javahost#1]
```
2015-06-17 16:31:18,907 [19] ERROR (500.jsp._jspService:67 - java.net.Inet6Address cannot be cast to java.net.Inet4Address
java.lang.RuntimeException: java.net.Inet6Address cannot be cast to java.net.Inet4Address
    at io.leopard.javahost.impl.AbstractDns.toHost(AbstractDns.java:93) ~[javahost-0.3-SNAPSHOT.jar:na]
    at io.leopard.javahost.impl.DnsImpl.list(DnsImpl.java:80) ~[javahost-0.3-SNAPSHOT.jar:na]
    at io.leopard.javahost.JavaHost.printAllVirtualDns(JavaHost.java:120) ~[javahost-0.3-SNAPSHOT.jar:na]
```

版本0.3-SNAPSHOT
恐怕得先做个判断再强制转换了

```
for (int i = 0; i < addresses.length; i++) {
                Inet4Address address = (Inet4Address) addresses[i];
```

**Comment by oldratlee** [comment]
@juforg [java-dns-cache-manipulator](https://github.com/alibaba/java-dns-cache-manipulator/tree/master/library)项目实现和加强了此项目的功能，测试了11个版本`jdk`的完整功能，应该没有你的问题，你可以试试～ 如有问题欢迎反馈 :smile:

**Comment by tanhaichao** [comment]
这个问题已在0.3-SNAPSHOT修复
